MAP_CENTER = (47.1557, 27.6064)
MAP_DIST = 350
GEOJSON_FILE = "camine_tuiasi.geojson"

WIND_ANGLE = 45 #de modificat posibilitatea sa se aleaga din interfata directia vantului
MAX_SMOKE = 200
TARGET_POPULATION_MIN = 300 #de modificat in functie de baza de date
TARGET_POPULATION_MAX = 450

FIREFIGHTER_SPEED = 6.0
TRUCK_DELAY_MIN = 80
TRUCK_DELAY_MAX = 150
FIRST_TRUCK_THRESHOLD = 6.0

WATER_SPEED = 6.5
WATER_RANGE = 100
FIRE_RATE_DELAY_MIN = 10
FIRE_RATE_DELAY_MAX = 18
WATER_DROP_LIFE = 20
BASE_EXTINGUISH_POWER = 0.25

TRUCK_AWARENESS_RANGE = 15.0
PANIC_CONTAGION_RANGE = 12.0
PANIC_CHANCE = 0.1
PANIC_HEAT_ZONE = 25.0

FIRE_GROWTH_MIN = 0.04
FIRE_GROWTH_MAX = 0.08
MAX_FIRE_RADIUS_SOFT_CAP = 22.0